name: my_first_workflow

on:
    push:
        branches: 
        - main
        tag: 
        - v*.*

jobs:
    my_first_cl:
    name: my_first_cl
    runs-on: ubuntu-latest
        steps:
        - name: check out
          uses: actions/checkout@v4
        - name: Check tag format
          run: |
            if [[ "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+$ ]]; then
              echo "Tag format is valid"
            else
              echo "Tag format is invalid. Please use v<digit>.<digit> format."
              exit 78
            fi

        - name: Check commit message
          run: |
            if [[ "$(git log --format=%s -n 1)" =~ ^#NORUN.*$ ]]; then
              echo "Commit message starts with #NORUN, exiting..."
              exit 78
            fi

        - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
        - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

        

        

    
        

        

            




